### ISSUE TITLE
Nested where-blocks: a helper's own where-helpers are never emitted by codegen (check-green, compile fails with unknown func)

### ISSUE THREAD

**Issue by aallan** [aallan/vera#978]
## Summary

A `where`-helper that carries its **own** `where` block (a nested helper) passes `vera check` and `vera verify`, but `vera compile` fails: the grandchild function is never emitted, so the WAT references an unknown function.

```vera
public fn outer(@Int -> @Int)
  requires(true) ensures(true) effects(pure)
{
  child(@Int.0)
} where {
  fn child(@Int -> @Int)
    requires(true) ensures(true) effects(pure)
  {
    grandchild(@Int.0 + 1)
  } where {
    fn grandchild(@Int -> @Int)
      requires(true) ensures(true) effects(pure)
    {
      @Int.0 * 2
    }
  }
}
```

- `vera check` → OK
- `vera verify` → OK
- `vera compile` → `WAT compilation failed: unknown func … $grandchild` at the `return_call $grandchild` site — `child`'s body is compiled (and its call lowered), but `grandchild` itself is never emitted.

## Classification

Check-green-then-compile-fail on a valid program — the same loud front-end/back-end divergence family as the fixed #969, one nesting level down: the checker checks nested `where` blocks recursively (`_check_fn` recurses into `where_fns`), but codegen's function-emission walk evidently collects only the top-level function's direct `where_fns`, not helpers-of-helpers. Loud (E699-family WAT failure), never a wrong value.

Grammar, checker, and verifier all accept the nested shape, so either codegen emits nested helpers (recursive collection) or the checker rejects nesting — reconcile per DESIGN, as with #969/#973.

Found during PR #977's test-coverage review (the nested-where positive-path probe); reproduced identically at base v0.1.4 (935120a) and at the PR head, so it is not introduced by #969's fix.

**Comment by aallan** [comment]
Root cause (from the PR #977 adversarial panel, confirmed by two independent skeptics): codegen's Pass-2 emission loop (`vera/codegen/core.py` ~754-758) compiles only ONE level of `decl.where_fns`, and `_compile_fn` (`vera/codegen/functions.py`) never recurses into a helper's own `where_fns` — while the registration path (`vera/codegen/registration.py` ~90-92) DOES recurse, so the grandchild's name is registered but its body is never emitted (`unknown func $grandchild` at WAT assembly). The generic path is unaffected: `vera/codegen/monomorphize.py` `_hoist_where_fns_under` recurses, so the identical program with a `forall<T>` parent compiles and runs. Single-level nesting also works. The checker (`_check_fn`) recurses into nested where-blocks, so the shape is fully accepted up front.

**Comment by aallan** [comment]
Root cause: the non-generic codegen Pass-2 loop emitted exactly one level of `where_fns`, while registration recurses over the full helper tree — so a grandchild helper's *name* was registered (its caller's body lowered to `call $grandchild`) but its body was never compiled, leaving a dangling reference that failed `vera compile` with the internal unknown-func error. The generic path was never affected because `_hoist_where_fns_under` already recurses per monomorphized clone, and the verifier already descends nested helpers (a probe with a false grandchild `ensures` is correctly rejected by `vera verify`), so the fix is confined to the emission loop: a `_flatten_where_fns` pre-order walk now feeds Pass 2 the full tree.

Fixed by https://github.com/aallan/vera/pull/989 (RED-first 2/3-level run tests + generic-parent control, mutation-validated, `ch05_nested_where_helpers.vera` conformance program). Merged into `release/v0.1.4`; this issue closes when the release branch lands on `main`.
