### PR TITLE
fix(codegen): emit nested where-helpers on the non-generic path

### LINKED ISSUE #978: Nested where-blocks: a helper's own where-helpers are never emitted by codegen (check-green, compile fails with unknown func)
## Summary

A `where`-helper that carries its **own** `where` block (a nested helper) passes `vera check` and `vera verify`, but `vera compile` fails: the grandchild function is never emitted, so the WAT references an unknown function.

```vera
public fn outer(@Int -> @Int)
  requires(true) ensures(true) effects(pure)
{
  child(@Int.0)
} where {
  fn child(@Int -> @Int)
    requires(true) ensures(true) effects(pure)
  {
    grandchild(@Int.0 + 1)
  } where {
    fn grandchild(@Int -> @Int)
      requires(true) ensures(true) effects(pure)
    {
      @Int.0 * 2
    }
  }
}
```

- `vera check` → OK
- `vera verify` → OK
- `vera compile` → `WAT compilation failed: unknown func … $grandchild` at the `return_call $grandchild` site — `child`'s body is compiled (and its call lowered), but `grandchild` itself is never emitted.

## Classification

Check-green-then-compile-fail on a valid program — the same loud front-end/back-end divergence family as the fixed #969, one nesting level down: the checker checks nested `where` blocks recursively (`_check_fn` recurses into `where_fns`), but codegen's function-emission walk evidently collects only the top-level function's direct `where_fns`, not helpers-of-helpers. Loud (E699-family WAT failure), never a wrong value.

Grammar, checker, and verifier all accept the nested shape, so either codegen emits nested helpers (recursive collection) or the checker rejects nesting — reconcile per DESIGN, as with #969/#973.

Found during PR #977's test-coverage review (the nested-where positive-path probe); reproduced identically at base v0.1.4 (935120a) and at the PR head, so it is not introduced by #969's fix.

### PR DESCRIPTION
**Pull request by aallan**
## Summary

Fixes #978 — a `where`-helper that carries its **own** `where`-helpers had those grandchildren registered by the checker but never emitted by the non-generic codegen path, so a check-green, verify-green program failed `vera compile` with an internal unknown-func error (`failed to find name $grandchild`) at the grandchild's call site.

## Root cause and fix

Registration recurses (`registration.py` registers the full helper tree, which is why the child's body happily lowers its call to `$grandchild`), and the generic path recurses (`_hoist_where_fns_under` hoists the full tree per monomorphized clone) — but the non-generic Pass-2 emission loop compiled exactly one level of `decl.where_fns`. The name existed; the body didn't.

The fix is confined to that loop: a `_flatten_where_fns` walk (pre-order DFS with an `id`-keyed visited guard) feeds Pass 2 the full helper tree, so every registered helper is emitted. **The verifier needs no change** — it already descends nested helpers, proven during grounding with a probe where the grandchild carries a false `ensures` that `vera verify` correctly rejects. Scope rules from #969/#977 are untouched (each helper stays a closed, param-rooted scope).

## Evidence

- RED-first: 2-level and 3-level run-level tests failed at base with the exact unknown-func error, green after; a generic-parent control is green on both sides (pins the path that already worked).
- Mutation-validated: reverting the recursion to one level turns both nested tests RED while the control stays green.
- `tests/conformance/ch05_nested_where_helpers.vera` (the 151st program, `run` level) exercises 2- and 3-level chains end-to-end with leaf-distinguishing values, each helper carrying a meaningful `ensures` discharged at Tier 1.
- Full gate: 7,048 passed (suite total 7,141), mypy clean, 151 conformance, 37 examples, doc gates green.

## Docs lockstep

#978 rows removed from KNOWN_ISSUES.md and SKILL.md; CHANGELOG `[Unreleased]` bullet; counts reconciled across TESTING/README/FAQ/ROADMAP/CLAUDE/AGENTS and the generated site assets; spec §5.6.2 checked — it never claimed a single-level restriction, so no spec change.

Closes #978

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed code generation to emit nested `where` helper functions recursively to arbitrary depth, ensuring correct runtime behavior and eliminating `eq`/`compare` divergence.
  - Fixed cross-module compilation for imported functions so nested `where` helper chains are fully registered and executed.

- **Tests**
  - Added regression coverage for multi-level nested `where` helper emission and runtime execution (generic-parent and imported-module scenarios).
  - Expanded the conformance suite to **151** programs.

- **Documentation**
  - Updated project/testing/conformance metrics to **7,169** tests and **151** conformance programs, and refreshed known-issues entries accordingly.

### CODE REVIEW

**Comment by aallan** [comment]
## Review round — 3 pr-review agents + 3-lens adversarial panel

Standard burndown gauntlet: code-reviewer, pr-test-analyzer, comment-analyzer, plus an adversarial panel (flagged-edges, pathological-shapes, and corpus-differential lenses; findings verified by two skeptics each). All in-scope findings are fixed in `4f016e2`; pre-existing bugs surfaced by the review are filed with tracker rows riding this PR.

### In-scope fixes (RED-first, mutation-validated per fix)

1. **Ability-op rewrite didn't recurse** (code-reviewer, monkey-patch-verified). `eq(...)`/`compare(...)` in a *grandchild* helper's body or contracts stayed a raw call — the body was skipped and the parent's call dangled with the same unknown-func failure this PR closes (native `==` at depth was fine, which pinned the cause). `_rewrite_where_fns` now recurses through the helper tree, mirroring `_flatten_where_fns`; three run-level tests pin the eq-body / eq-contract / compare-body shapes.
2. **Imported-module registration didn't recurse** (panel, two-skeptic confirmed, base-differential verified). An imported function's grandchild helper was checked and Tier-1-verified but never appended for Pass-2.5 emission — the cross-module twin of #978. The registration loop now uses the shared `_flatten_where_fns`; two cross-module tests pin a grandchild chain (runs to 16) and a 3-level chain.
3. **Branching-at-depth was untested** (test-analyzer, criticality 6). Every committed shape was a linear chain; a mutant dropping non-first *nested* subtrees escaped the entire suite and all 151 conformance programs. One test (`outer → ha → {ha1, ha2}` → 50) now kills both branch-dropping mutants — demonstrated RED under the mutant before landing.
4. Stale docstring reframed (comment-analyzer): a checker test still described the codegen path as "unimplemented, tracked as #978".

### Pre-existing bugs filed (all base-identical, none regressions — verified against 3efad78)

- **#990** — a `forall<T>` helper under a non-generic parent is never monomorphized: check/verify green, compile unknown-func (loud; the verifier honestly Tier-3s the caller). Top-level-only generic discovery.
- **#991** — duplicate helper names crash WAT assembly with a raw `duplicate func identifier` instead of a diagnostic; before this PR's base, one variant (helper named like a top-level fn) ran to a **silently wrong value** — the #978 fix upgraded that to a loud failure. The verifier's same-named-helper lookup also disagrees with the checker's (false E500 on one diamond shape, confirmed on the issue).
- **#992** — imported bodies never receive the ability-op rewrite at *any* level: `eq`/`compare` in any imported function fails compile on a check/verify-green pair (found by this round's symmetry probe).

### Panel clean checks (highlights of 24)

Depth-6 chains, wide trees (3×2), and a 50,000-deep self-recursive *nested* helper (TCO holds) all compile and run correctly; mutual recursion between siblings' nested helpers is admitted and works; the generic path's per-clone name mangling is confirmed correct (the flat-name collision is non-generic-only); the corpus differential across all 187 files shows the base→head delta is exactly the new conformance program (+17 Tier-1 / +17 Tier-3 / +1 ok) with all 10 negative fixtures identical; De Bruijn slot integrity holds at depth with same-typed params and non-commutative ops; runtime contract traps fire correctly at grandchild depth with correct backtraces.

Suite after the round: 7,074 passed (total 7,167), mypy clean, 151 conformance, 37 examples, doc gates green.

File: vera/codegen/core.py [hunk 1]
```diff
@@ -762,12 +762,21 @@ def compile_program(self, program: ast.Program) -> CompileResult:
...
+                    # registered and the parent's body lowers its call to
+                    # `$grandchild` — but before #978 only the direct helpers
+                    # were emitted, so a nested helper's body dangled
+                    # (`unknown func` at WAT assembly).  The generic path
+                    # already flattens nested helpers via
+                    # `monomorphize._hoist_where_fns_under`.
+                    for wfn in self._flatten_where_fns(decl):
+                        wfn_wat = self._compile_fn(wfn, export=False)
+                        if wfn_wat is not None:
+                            functions_wat.append(wfn_wat)
```
[the remark this answers is not in the document]
Comment (aallan) [reply vera/codegen/core.py:779]: @coderabbitai Verified against current code and empirically refuted, with one regression pin added in f4c507c. The Pass-2.5/2.6 compile sites at core.py:804/:839 iterate self._imported_fn_decls, which the round-2 fix (4f016e2) pre-flattens at the REGISTRATION site (modules.py now walks the helper tree via the shared _flatten_where_fns) — so the compile loops need no where_fns walk of their own. Three end-to-end variants all run correctly at head: plain imported grandchild chain (16) and 3-level chain (116) pinned by TestImportedNestedWhereEmission989; a locally-shadowed imported fn reaching its nested grandchild through the module-qualified call (116, the Pass-2.6 mod$… path this comment names) — probed during this round and now pinned by test_shadowed_imported_fn_nested_helpers_run in f4c507c; and a locally-shadowed HELPER name (1016, correct binding both sides). No dangling $grandchild is reachable through either pass.

File: tests/test_codegen_monomorphize.py [hunk 2]
```diff
@@ -3186,6 +3186,100 @@ def test_where_helper_calls_another_generic(self) -> None:
...
+    fn grandchild(@Int -> @Int) requires(true) ensures(true) effects(pure)
+    { @Int.0 * 2 }
+  }
+}
+public fn main(@Unit -> @Int) requires(true) ensures(true) effects(pure)
+{ outer(99) }
+"""
+        assert _run(source, fn="main") == 12
+
+
```
[the remark this answers is not in the document]
Comment (aallan) [reply tests/test_codegen_monomorphize.py:3427]: @coderabbitai Coverage exists — it lives in tests/test_codegen_modules.py (where the cross-module suite is), not test_codegen_monomorphize.py: TestImportedNestedWhereEmission989 (added in 4f016e2) pins the imported grandchild chain end-to-end (check-green/verify-green/compile-green/run==16) and a 3-level imported chain (116), and f4c507c adds the locally-shadowed variant through the Pass-2.6 mod$… emission (116). The monomorphize file keeps the local-path and generic-hoisting tests only.

File: tests/test_codegen_monomorphize.py [hunk 3]
```diff
@@ -3186,6 +3186,215 @@ def test_where_helper_calls_another_generic(self) -> None:
...
+      ensures(eq(@Int.result, @Int.result))
+      effects(pure)
+    { @Int.0 }
+  }
+}
+public fn main(@Unit -> @Int) requires(true) ensures(true) effects(pure)
+{ outer(7) }
+"""
+        assert _run(source, fn="main") == 7
+
```
[the remark this answers is not in the document]
Comment (aallan) [reply tests/test_codegen_monomorphize.py:3345]: @coderabbitai Fixed in 696dfcf — the mislabeled test is renamed test_nested_where_grandchild_eq_contract_runs (it exercises eq-in-contract, kept as that cell), and a real test_nested_where_grandchild_compare_contract_runs completes the {eq, compare} x {body, contract} matrix: compare in a grandchild's ensures (matched on Greater/Equal/Less), which goes RED under a recursion-neutered mutant of _rewrite_where_fns — so the compare rewrite's if-chain AST through the _rewrite_ops_in_contracts entry point is now provably exercised.

File: KNOWN_ISSUES.md [hunk 4]
```diff
@@ -9,8 +9,10 @@ Defects in shipped compiler, runtime, or tooling behaviour — this table matche
...
+| Duplicate `where`-helper names (two siblings' nested helpers sharing a name, or a helper named like a top-level function) crash WAT assembly with a raw `duplicate func identifier` error instead of a diagnostic — non-generic helper WAT names are flat and unmangled, and nothing rejects the collision (the generic path already mangles per-clone). Needs either a checker diagnostic or non-generic parent-qualified mangling; checker, verifier, and codegen must agree on helper-name scoping. | [#991](https://github.com/aallan/vera/issues/991) |
+| Imported function bodies never receive the ability-op rewrite — `eq(...)`/`compare(...)` in any imported function (top-level, `where`-helper, or nested helper) stays a raw call codegen cannot lower, so `vera compile` on the importing program fails with an internal unknown-func error on a check-green, verify-green pair. Native operators are unaffected. Running the (now-recursive) rewrite over the imported-decl set before Pass 2.5 is the fix. | [#992](https://github.com/aallan/vera/issues/992) |
```
[the remark this answers is not in the document]
Comment (aallan) [reply KNOWN_ISSUES.md:15]: @coderabbitai Fixed in 696dfcf — the SKILL workaround cell is now type-correct: eq(a, b) → == is the only drop-in replacement; compare(...) returns Ordering, so match-on-Ordering callers must build the Ordering explicitly (an if-chain) or keep compare out of imported modules until #992 lands. (The KNOWN_ISSUES row itself never suggested operator substitution — the overpromise was only in the SKILL workaround cell.)
